name: CI-CD

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      - name: Create .env file
        run: |
          echo "DB_URL=${{ secrets.DB_URL }}" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "CORS_ORIGINS=${{ secrets.CORS_ORIGINS }}" >> .env

      - name: Start application
        run: docker compose up -d --build

      - name: Wait for application
        run: |
          sleep 10
          docker compose ps

      - name: Install Playwright Browsers
        run: |
          cd frontend
          npx playwright install --with-deps

      - name: Run Playwright Tests
        run: |
          cd frontend
          npx playwright test --project=chromium

      - name: Show logs on failure
        if: failure()
        run: docker compose logs
